export const RECEIPT_STORE_NAME = 'MWAMBA LIQUOR STORES';
export const RECEIPT_LOCATION = 'BEE CENTER';
export const RECEIPT_PHONE = 'Tel: +254 745 119 135';
export const RECEIPT_PAYMENT_DETAILS = 'TILL:8856092';

export const RECEIPT_STORE_DETAILS = [
  RECEIPT_LOCATION,
  RECEIPT_PHONE,
  RECEIPT_PAYMENT_DETAILS,
];
